sudo: required
services:
    - docker

before_install:
    - docker build -t srisathiya01/docker-react -f Dockerfile.dev  .

script:
    - docker run srisathiya01/docker-react npm run test -- --coverage